<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-E5NCT7NC" failures="1" tests="1" name="Test" time="0.218" errors="0" timestamp="2022-04-27T19:02:54 IST">
  <testcase classname="com.bank.testcases.TC_AddCustomerTest_003" name="addNewCustomer" time="0.0">
    <failure type="org.testng.TestNGException" message="
Method public void com.bank.testcases.TC_AddCustomerTest_003.addNewCustomer(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.InterruptedException,java.io.IOException requires a @DataProvider named : customer data">
      <![CDATA[org.testng.TestNGException: 
Method public void com.bank.testcases.TC_AddCustomerTest_003.addNewCustomer(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.InterruptedException,java.io.IOException requires a @DataProvider named : customer data
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- addNewCustomer -->
</testsuite> <!-- Test -->
